Algoritmo "Ex 4"

//Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.


Var
n1, n2: inteiro

Inicio
Escreval ("Digite o primeiro número: ")
Leia (n1)
Escreval ("Digite o segundo número: ")
Leia (n2)
Escreval ("A soma entre ", n1," e ", n2," é igual a ", n1+n2)



Fimalgoritmo