Algoritmo "Ex 15"

//Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.

Var
dias_trabalhados: inteiro
salario, salario_dia: real


Inicio
salario_dia <- 8*25
Escreva ("Digite quantos dias foram trabalhados em um mês: ")
leia (dias_trabalhados)
Escreval ("Seu salário no mês foi de:R$",salario_dia*dias_trabalhados)





Fimalgoritmo