Algoritmo "Ex 42"

//42) Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

Var
contador, numero: inteiro


Inicio
Escreval ("Digite um número que seja inteiro e positivo: ")
Leia (numero)

LimpaTela
contador <- 1
Para contador de 1 ate numero faca
     Escreval (contador)
FimPara

Escreval (" Acabou!")


Fimalgoritmo