Algoritmo "Ex 66"
//66) Escreva um programa que leia um número qualquer e mostre a tabuada desse
//número, usando a estrutura “para”.
//Ex: Digite um valor: 5
//5 x 1 = 5
//5 x 2 = 10
//5 x 3 = 15 ...

Var
contador, numero: inteiro

Inicio

Escreval("Digite um número e te darei a tabuada: ")
Leia(numero)

para contador de 1 ate 10 faca
Escreval(numero, " x ", contador  ," = ", numero*contador)
fimpara

Fimalgoritmo