Algoritmo "EX 67"

//67) Faça um programa usando a estrutura “para” que leia um número inteiro
//positivo e mostre na tela uma contagem de 0 até o valor digitado:
//Ex: Digite um valor: 9
//Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!

Var
contador, numero: inteiro


Inicio
Escreval ("Escreva um número e te mostrarei do 0 até seu número: ")
Leia (numero)

Para contador de 0 ate numero Faça
     Escreva (contador ,", ")
FimPara

Escreval ("FIM!")
     

Fimalgoritmo